# Generated by Django 2.1 on 2018-10-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Email_Address', models.EmailField(max_length=100)),
                ('Job_Title', models.CharField(max_length=100)),
                ('Business_Phone', models.CharField(default='None', max_length=25)),
                ('Home_Phone', models.CharField(default='None', max_length=25)),
                ('Mobile_Phone', models.CharField(default='None', max_length=25)),
                ('Fax_Number', models.CharField(default='None', max_length=25)),
                ('Address', models.CharField(max_length=250)),
                ('City', models.CharField(max_length=100)),
                ('State_Province', models.CharField(max_length=100)),
                ('ZIP', models.PositiveIntegerField()),
                ('Country_Region', models.CharField(default='United States of America', max_length=100)),
                ('Web_Page', models.URLField(max_length=100)),
                ('Notes', models.TextField(default='None')),
            ],
        ),
    ]
