# Generated by Django 2.1 on 2018-10-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181010_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Username',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
