# Generated by Django 2.1 on 2018-08-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='date_performed',
            field=models.DateField(auto_now=True),
        ),
    ]
