# Generated by Django 2.1 on 2018-08-31 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_time_date_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
