# Generated by Django 2.1 on 2018-09-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180831_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_code',
            field=models.CharField(default='Misc.', max_length=200),
            preserve_default=False,
        ),
    ]
