# Generated by Django 2.1 on 2018-09-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_task_task_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_text',
        ),
        migrations.AddField(
            model_name='time',
            name='task_text',
            field=models.CharField(default='Miscellaneous', max_length=200),
            preserve_default=False,
        ),
    ]
