# Generated by Django 2.1 on 2018-09-18 14:23

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('tracker', '0006_auto_20180918_0905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
    ]
