# Generated by Django 2.1 on 2018-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20180918_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='date_performed',
            field=models.DateField(),
        ),
    ]
