# Generated by Django 2.1 on 2018-10-10 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_employees'),
        ('tracker', '0008_auto_20180925_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('Billable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Worked', models.DateField()),
                ('Hours', models.SmallIntegerField(default=0)),
                ('Minutes', models.IntegerField(default=0)),
                ('Work_Description', models.CharField(max_length=200)),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Employees')),
                ('Work_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.WorkCodes')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_code',
        ),
        migrations.RemoveField(
            model_name='time',
            name='task_performed',
        ),
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
