# Generated by Django 2.1 on 2018-10-10 21:40

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('login', '0004_auto_20181010_1640'),
        ('tracker', '0009_auto_20181010_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkCodes',
            new_name='WorkCode',
        ),
        migrations.RenameModel(
            old_name='WorkHours',
            new_name='WorkHour',
        ),
    ]
