# Generated by Django 2.1 on 2018-10-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20181015_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCategory', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cat',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='cat',
            name='Subcategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracker.SubCat'),
            preserve_default=False,
        ),
    ]
