# Generated by Django 2.1 on 2018-10-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20181016_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='Subcategory',
        ),
        migrations.AddField(
            model_name='subcat',
            name='Parent_Category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tracker.Cat'),
            preserve_default=False,
        ),
    ]
