# Generated by Django 2.1 on 2018-10-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20181016_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhour',
            name='Task_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.SubCat'),
        ),
    ]
